name: Terraform Deploy

on:
  workflow_run:
    workflows: ["Terraform Build"]  
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: azure_data_platform/terraform/backend

      - name: Terraform Init
        run: terraform init
        working-directory: azure_data_platform/terraform/backend
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          ARM_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.tenantId }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: azure_data_platform/terraform/backend
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          ARM_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.tenantId }}